baseURL: https://jaelyn-shi.netlify.app
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: Jaelyn's Website
params:
  address: London Business School, Regent's Park, NW1 4SA, London, UK
  author: Jaelyn Shi
  baidu_analytics_id: ''
  baidu_site_verification: ''
  contact:
    enable: yes
    form_action: '#'
#  cookies:
#    enable: yes
#    expire_days: 2
  copyright: Copyright &copy; 2022 by Jaelyn Shi
  description: This is meta description
  email: doreen_slj@hotmail.com
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: yes
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  phone: +44 078 1837 7676
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    #- URL: '#'
    #  icon: ti-facebook
    - URL: 'https://www.instagram.com/jaelyn.1003/'
      icon: ti-instagram
    #- URL: '#'
    #  icon: ti-dribbble
    #- URL: '#'
    #  icon: ti-twitter-alt
    - URL: 'https://www.linkedin.com/in/jaelyn-s-a21355196/'
      icon: ti-linkedin
      
  theme_color: '#41228e'
menu:
  main:
    - URL: about/
      name: About
      weight: 1
    - URL: blog/
      name: Blog
      weight: 2
    # - URL: portfolio/
    #   name: Projects
    #   weight: 3
    - URL: contact/
      name: Contact
      weight: 4
